
["Entity Settings"]
	#Defines how often a goat will try to grow its fur, the growth cooldown after shearing, and the chance of it succeeding
	#Format: [ticks, cooldown, chance]
	"Goat Fur Growth Timings" = [1200, 2400, 0.2]
	#List of entities that will insulate the player when riding them
	#Format: ["entity_id", insulation]
	#(1 is complete insulation, 0 is no insulation)
	"Insulated Entities" = []

["Mob Spawning"]
	#Defines the biomes that Chameleons can spawn in
	#Format: [["biome_id", weight], ["biome_id", weight], etc...]
	"Chameleon Spawn Biomes" = [["minecraft:bamboo_jungle", 80], ["minecraft:jungle", 80], ["minecraft:sparse_jungle", 35], ["minecraft:desert", 1], ["byg:tropical_rainforest", 60], ["byg:jacaranda_forest", 3], ["byg:guiana_shield", 3], ["byg:crag_gardens", 4], ["byg:atacama_desert", 1], ["byg:cypress_swamplands", 3], ["byg:mojave_desert", 1], ["byg:windswept_desert", 2]]
	#Defines additional biomes that goats can spawn in
	#Format: [["biome_id", weight], ["biome_id", weight], etc...]
	#Not affected by the "Increase Goat Spawns" option
	"Goat Spawn Biomes" = [["minecraft:frozen_peaks", 8], ["minecraft:jagged_peaks", 8], ["minecraft:snowy_slopes", 8], ["minecraft:meadow", 3], ["minecraft:windswept_hills", 6], ["minecraft:windswept_forest", 6], ["minecraft:windswept_gravelly_hills", 4], ["minecraft:grove", 5], ["minecraft:stony_peaks", 8], ["byg:canadian_shield", 3], ["byg:guiana_shield", 3], ["byg:fragment_forest", 128], ["byg:howling_peaks", 6], ["byg:shattered_glacier", 6], ["byg:dacite_ridges", 5]]

