
["Fuel Items"]
	#Defines items that can be used as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	Boiler = [["minecraft:coal", 37], ["minecraft:charcoal", 37], ["minecraft:coal_block", 333], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000]]
	Icebox = [["minecraft:snowball", 37], ["minecraft:clay", 37], ["minecraft:snow_block", 333], ["minecraft:water_bucket", 333], ["minecraft:ice", 333], ["minecraft:packed_ice", 1000]]
	#Negative values indicate cold fuel
	Hearth = [["minecraft:coal", 37], ["minecraft:charcoal", 37], ["minecraft:coal_block", 333], ["minecraft:magma_block", 333], ["minecraft:lava_bucket", 1000], ["minecraft:snowball", -37], ["minecraft:clay", -37], ["minecraft:snow_block", -333], ["minecraft:water_bucket", -333], ["minecraft:ice", -333], ["minecraft:packed_ice", -1000]]
	#If true, potions can be used as fuel in the hearth
	#This gives all players in range the potion effect
	"Allow Potions in Hearth" = true
	#Potions containing any of these effects will not be allowed in the hearth
	#Format: ["effect_id", "effect_id", ...etc]
	"Blacklisted Hearth Potions" = ["minecraft:instant_damage", "minecraft:poison", "minecraft:wither", "minecraft:weakness", "minecraft:mining_fatigue", "minecraft:slowness"]

["Soulspring Lamp"]
	#Defines items that the Soulspring Lamp can use as fuel
	#Format: [["item-id-1", amount-1], ["item-id-2", amount-2], ...etc]
	"Fuel Items" = [["cold_sweat:soul_sprout", 4]]
	#Defines the dimensions that the Soulspring Lamp can be used in
	#Format: ["dimension-id-1", "dimension-id-2", ...etc]
	"Valid Dimensions" = ["minecraft:the_nether"]

[Insulation]
	#Defines the items that can be used for insulating armor in the Sewing Table
	#Format: [["item_id", cold, hot, "static", *nbt], ["item_id", amount, adapt-speed, "adaptive", *nbt], ...etc]
	#"item_id": The item's ID (i.e. "minecraft:iron_ingot"). Accepts tags with "#" (i.e. "#minecraft:wool").
	#
	#Adaptive Insulation: 
	#"amount": The amount of insulation the item provides.
	#"adapt-speed": The speed at which the insulation adapts to the environment.
	#*"type": Optional. Either "static" or "adaptive". Defines the insulation type. Defaults to static.
	#*"nbt": Optional. If set, the item will only provide insulation if it has the specified NBT tag.
	#
	#Static Insulation: 
	#"cold": The amount of cold insulation the item provides.
	#"hot": The amount of heat insulation the item provides.
	#*"type": Optional. Either "static" or "adaptive". Defines the insulation type. Defaults to static.
	#*"nbt": Optional. If set, the item will only provide insulation if it has the specified NBT tag.
	"Insulation Ingredients" = [["cold_sweat:hoglin_hooves", 0.0, 8.0], ["cold_sweat:hoglin_hide", 0.0, 2.0], ["minecraft:gray_wool", 1.5, 0.0], ["minecraft:lime_wool", 1.5, 0.0], ["minecraft:purple_wool", 1.5, 0.0], ["minecraft:pink_wool", 1.5, 0.0], ["minecraft:leather_chestplate", 6.0, 6.0], ["cold_sweat:hoglin_trousers", 0.0, 10.0], ["minecraft:light_blue_wool", 1.5, 0.0], ["minecraft:light_gray_wool", 1.5, 0.0], ["minecraft:leather_helmet", 4.0, 4.0], ["minecraft:leather", 1.0, 1.0], ["minecraft:orange_wool", 1.5, 0.0], ["minecraft:black_wool", 1.5, 0.0], ["minecraft:yellow_wool", 1.5, 0.0], ["minecraft:blue_wool", 1.5, 0.0], ["minecraft:rabbit_hide", 0.0, 1.5], ["minecraft:cyan_wool", 1.5, 0.0], ["minecraft:green_wool", 1.5, 0.0], ["minecraft:magenta_wool", 1.5, 0.0], ["minecraft:red_wool", 1.5, 0.0], ["minecraft:leather_leggings", 5.0, 5.0], ["minecraft:leather_boots", 4.0, 4.0], ["cold_sweat:hoglin_tunic", 0.0, 12.0], ["cold_sweat:hoglin_headpiece", 0.0, 8.0], ["minecraft:brown_wool", 1.5, 0.0], ["minecraft:white_wool", 1.5, 0.0]]
	#Defines the items that provide insulation when worn
	#See Insulation Ingredients for formatting
	"Insulating Armor" = [["cold_sweat:hoglin_headpiece", 0.0, 8.0], ["cold_sweat:hoglin_tunic", 0.0, 12.0], ["minecraft:leather_helmet", 4.0, 4.0], ["cold_sweat:hoglin_hooves", 0.0, 8.0], ["minecraft:leather_chestplate", 6.0, 6.0], ["cold_sweat:hoglin_trousers", 0.0, 10.0], ["minecraft:leather_leggings", 5.0, 5.0], ["minecraft:leather_boots", 4.0, 4.0]]
	#Defines how many insulation slots armor pieces have
	#Format: [head, chest, legs, feet]
	"Insulation Slots" = [4, 6, 5, 4]
	#Defines wearable items that cannot be insulated
	#Format: ["item_id", "item_id", ...etc]
	"Insulation Blacklist" = []

[Consumables]
	#Defines items that affect the player's temperature when consumed
	#Format: [["item_id", amount], ["item_id", amount], ...etc]
	#Negative values are cold foods, positive values are hot foods
	"Temperature-Affecting Foods" = []
	#Defines how much a waterskin will change the player's body temperature by when used
	#Range: > 0
	"Waterskin Strength" = 50

