
#Format: [["dimension_1", temperature1], ["dimension_2", temperature2]... etc]
#Common dimension IDs: minecraft:overworld, minecraft:the_nether, minecraft:the_end
#Note: all temperatures are in Minecraft units
#°F to MC = (x - 32) / 42
#°C to MC = x / 23.3
[Dimensions]
	#Applies an offset to the world's temperature across an entire dimension
	"Dimension Temperature Offsets" = [["minecraft:the_end", -0.1, "MC"], ["minecraft:the_nether", 0.7, "MC"]]
	#Overrides existing dimension temperatures & offsets
	#Also overrides temperatures of all biomes in the dimension
	"Dimension Temperatures" = []

#Format: [["biome_1", tempLow, tempHigh, *units], ["biome_2", tempLow, tempHigh, *units]... etc]
#temp-low: The temperature of the biome at midnight
#temp-high: The temperature of the biome at noon
#units: Optional. The units of the temperature ("C" or "F". Defaults to MC units)
#Note: all temperatures are in Minecraft units
[Biomes]
	#Applies an offset to the temperature of a biome (in Minecraft units).
	"Biome Temperature Offsets" = []
	#Defines the temperature of a biome, overriding existing biome temperatures & offsets (in Minecraft units).
	"Biome Temperatures" = [["byg:skyris_vale", 42.0, 68.0, "F"], ["byg:autumnal_valley", 58.0, 67.0, "F"], ["byg:autumnal_forest", 60.0, 75.0, "F"], ["byg:zelkova_forest", 44.0, 61.0, "F"], ["minecraft:savanna_plateau", 76.0, 98.0, "F"], ["byg:dacite_ridges", 40.0, 65.0, "F"], ["minecraft:taiga", 44.0, 62.0, "F"], ["minecraft:eroded_badlands", 88.0, 120.0, "F"], ["minecraft:savanna", 70.0, 95.0, "F"], ["byg:lush_stacks", 66.0, 75.0, "F"], ["minecraft:swamp", 72.0, 84.0, "F"], ["byg:baobab_savanna", 70.0, 95.0, "F"], ["byg:maple_taiga", 53.0, 71.0, "F"], ["minecraft:bamboo_jungle", 76.0, 87.0, "F"], ["byg:subzero_hypogeal", -10.0, -10.0, "F"], ["minecraft:frozen_peaks", 15.0, 33.0, "F"], ["minecraft:old_growth_spruce_taiga", 48.0, 62.0, "F"], ["minecraft:snowy_beach", 38.0, 52.0, "F"], ["byg:firecracker_shrubland", 72.0, 105.0, "F"], ["byg:cypress_swamplands", 68.0, 82.0, "F"], ["minecraft:warm_ocean", 67.0, 76.0, "F"], ["byg:autumnal_taiga", 56.0, 68.0, "F"], ["minecraft:windswept_forest", 48.0, 66.0, "F"], ["minecraft:jungle", 76.0, 87.0, "F"], ["minecraft:snowy_slopes", 24.0, 38.0, "F"], ["byg:dead_sea", 72.0, 82.0, "F"], ["byg:fragment_forest", 43.0, 64.0, "F"], ["minecraft:stony_shore", 50.0, 64.0, "F"], ["minecraft:soul_sand_valley", 33.0, 33.0, "F"], ["byg:frosted_taiga", 22.0, 48.0, "F"], ["minecraft:old_growth_birch_forest", 58.0, 72.0, "F"], ["minecraft:desert", 48.0, 115.0, "F"], ["minecraft:snowy_taiga", 19.0, 48.0, "F"], ["minecraft:badlands", 84.0, 120.0, "F"], ["minecraft:deep_frozen_ocean", 56.0, 65.0, "F"], ["minecraft:river", 60.0, 70.0, "F"], ["minecraft:old_growth_pine_taiga", 48.0, 62.0, "F"], ["byg:weeping_witch_forest", 56.0, 73.0, "F"], ["minecraft:windswept_savanna", 67.0, 90.0, "F"], ["minecraft:wooded_badlands", 80.0, 108.0, "F"], ["byg:frosted_coniferous_forest", 8.0, 31.0, "F"], ["byg:twilight_meadow", 49.0, 66.0, "F"], ["byg:coniferous_forest", 52.0, 70.0, "F"]]

#Format: [season-start, season-mid, season-end]
#Applied as an offset to the world's temperature
["Season Temperatures"]
	Summer = [0.4, 0.6, 0.4]
	Autumn = [0.2, 0, -0.2]
	Winter = [-0.4, -0.6, -0.4]
	Spring = [-0.2, 0, 0.2]

